### ISSUE TITLE
(dvbapi) camsocket:/var/camd.socket

### ISSUE THREAD

**Issue by AZBoxEmperador** [su-mak/his_test#1]
the OSCAM(r10670) give me this log and the only thing different from the other you built is the camsocket...

2018/10/22 21:45:49 B5224800 c dvbapi: HI_UNF_DMX_Init:(0)

2018/10/22 21:45:49 B5224800 c   (dvbapi) Detected Hisilicon{1}.
2018/10/22 21:45:49 B5224800 c   (dvbapi) mydvb:Hisilicon

2018/10/22 21:45:49 B5224800 c   (dvbapi) camsocket:/var/camd.socket

**Comment by su-mak** [comment]
https://github.com/su-mak/his_test/commit/1861c8b73978253efac3d58cfd6bae89457f410a

**Comment by AZBoxEmperador** [comment]
here is the log

[oscam.txt](https://github.com/su-mak/his_test/files/2508641/oscam.txt)

**Comment by AZBoxEmperador** [comment]
Another log

[oscam.txt](https://github.com/su-mak/his_test/files/2508702/oscam.txt)

**Comment by su-mak** [comment]
Try it...
https://github.com/su-mak/osebuild/tree/beta
Thanks!
